### ISSUE TITLE
[Types] Error: Property 'text' does not exist on type 'ContentBlock'.

### ISSUE THREAD

**Issue by davidstackio** [anthropics/anthropic-sdk-typescript#432]
After updating to `v0.22.0` from `v0.20.9`, I'm getting a type error on the last line of this block (`text = msg.content[0].text;`):

```ts
const msg = await anthropic.messages.create({
      model: "claude-3-opus-20240229",
      max_tokens: maxOutputTokens,
      temperature: 0.9,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "text",
              text: prompt,
            },
          ],
        },
      ],
    });
    text = msg.content[0].text;
```

The type error is:
```
Property 'text' does not exist on type 'ContentBlock'.
  Property 'text' does not exist on type 'ToolUseBlock'.ts(2339)
```

When logging the message content, it does not appear to have changed, so I'm guessing this is just a type bug that needs fixed. My code works as expected when adding the `// @ts-ignore` comment above the problem line, which is my current workaround.

**Comment by olu-an** [comment]
cc @rattrayalex to see if it's an SDK issue

**Comment by bcherny** [comment]
It seems like this is an intentional change introduced in https://github.com/anthropics/anthropic-sdk-typescript/pull/429.

Prior to that PR, response messages were always of type `text` (ie. content generated by Claude). After the PR, responses can be either `text`(as before) or `tool_use`, meaning Claude invoked an external tool.

To fix the TypeScript error, you'll want to refine Claude's response, to explicitly check which type of response it is. It is no longer safe to assume the response is always `text`:

```ts
const response = msg.content[0];
switch (response.type) {
  case 'text':
    const text = response.text;
    // ...
  case 'tool_use':
    // ...
}
```

You can also use `if` or any other conditional check to refine the response.

Alternatively, if you know the response will always be content (ie. you did not configure a tool), you can use a type assertion. Though, note this is not as typesafe as an explicit `if`:

```ts
const text = (msg.content[0] as Anthropic.TextBlock).text;
```

See https://docs.anthropic.com/en/docs/build-with-claude/tool-use#chain-of-thought

---

For Anthropic folks -- there's a minor improvement you might consider to make the SDK a bit easier to use: add an overloaded type signature to `create`, so that it returns `content` of type `ContentBlock` if `tool` is configured, and otherwise returns `content` of type `TextBlock`. That would make it so the PR above doesn't break builds for folks that don't use tools.

**Comment by rattrayalex** [comment]
Hey, sorry for the delay at taking a look here. @bcherny is correct that this is intentional, but I also quite like the overload idea. No guarantees we'll be able to get to it soon, but I'll shop it around.

**Comment by rattrayalex** [comment]
I'll leave this issue open, even though it is indeed Working As Intended, because I'd really like to improve the developer experience here.

**Comment by jonnicholson94** [comment]
Just to comment, I had this problem this morning - didn't find the docs too clear, and a bit hacky (in my opinion) to have to explicitly declare the type like that when it'll always be 'text' for my example. A solution would be great!

**Comment by kmankan** [comment]
is there a better solution to this yet? I was running into this for a while and couldn't really figure out from the type error what the problem was or how to address it. this thread was very useful though.

Also, amusingly, claude-3.5-sonnet doesn't easily immediately know how to fix this.

**Comment by carnivale7898** [comment]
Type guards to the rescue

```
import type {
  ContentBlock,
  TextBlock,
} from '@anthropic-ai/sdk/resources/messages'

export function isTextBlock(block: ContentBlock): block is TextBlock {
  return block.type === 'text'
}
```

And usage:
```
if (response.content[0] && isTextBlock(response.content[0]))
{
  return response.content[0].text
}
```

**Comment by HeskethGD** [comment]
This was also quite tricky to figure out in Python to get Pylance happy. Based on the above comments, the below seemed to work:

```python

response = self.client.messages.create(
      model="claude-3-sonnet-20240229",
      max_tokens=4000,
      temperature=0,
      system=system_message,
      messages=messages
  )

# Handle mixed content types - check if it's a TextBlock
# https://github.com/anthropics/anthropic-sdk-typescript/issues/432
if response.content:
    content_block = response.content[0]
    # Check if this is a text content block (not tool use)
    if content_block.type == "text":
        return content_block.text.strip()
    else:
        # Handle tool use or other content types
        raise ValueError(f"Non-text response received: {content_block.type}")
else:
    return ""
```

**Comment by ibedevesh** [comment]
Hit this again today on `@anthropic-ai/sdk@0.96.0`. The union has grown a bit since this thread started — `ContentBlock` is now `TextBlock | ToolUseBlock | ThinkingBlock | ...`, so the error message reads `Property 'text' does not exist on type 'ThinkingBlock'` rather than `ToolUseBlock`, which threw me for a second.

The switch-on-`type` approach @bcherny posted still works perfectly, just with the extra `case "thinking"` branch if you've enabled extended thinking. The reusable `isTextBlock` guard from @carnivale7898 also still type-checks cleanly. For anyone who just wants the assistant's text out as a string, this one-liner has been working well for me:

```ts
const getText = (msg: { content: ContentBlock[] }) =>
  msg.content.filter((b): b is TextBlock => b.type === "text").map(b => b.text).join("");
```

One small gotcha worth flagging: the type imports come from `@anthropic-ai/sdk/resources/messages`, not the package root — `import type { TextBlock } from "@anthropic-ai/sdk"` fails with a "no exported member" error. Tripped me up.

Wrote it all up with the three patterns + a 60-second repro here if it helps anyone else landing on this thread: https://npad.run/p/how-to-fix-property-text-does-not-exist-on-type-contentblock-j592g2v3mb

**Comment by dtmeadows-ant** [comment]
@davidstackio sorry for the long delay here. This is intentional — `content` holds a union of block types, so narrow on `type` before reading `.text` (background: https://github.com/anthropics/anthropic-sdk-typescript/issues/432#issuecomment-2178765160):

```ts
const block = msg.content[0];
if (block.type === 'text') {
  const text = block.text;
}
```

The return-type overload discussed here never shipped, so I'm closing this as working as intended, with the narrowing pattern above as the supported approach.
